<?php

/**
 * =============================
 * Controller
 * =============================
 */

if(isset($_GET["id"])){

	if(isset($_FILES) && !empty($_FILES) ){
		//fileUpload();
		mediaUpload();
	}

	if(isset($_POST["submit"]) && $_POST["submit"] == "save"){
		saveWohnung();
	}

	if(isset($_POST["submit"]) && $_POST["submit"] == "showImages"){
		loadImages();
	}

	if(isset($_POST["submit"]) && $_POST["submit"] == "saveMarker"){
		saveMarker();
	}

	if(isset($_POST["submit"]) && $_POST["submit"] == "deleteImg"){
		deleteImg();
	}

	renderWohnungFormular();

}else if(isset($_POST["submit"]) && $_POST["submit"] == "createWohnung"){

	if($_POST["submit"] == "createWohnung"){
		createWohnung();
	}

}else{
		renderWohnungen();

	if(isset($_POST["submit"]) && $_POST["submit"] == "delete"){
		deleteWohnung();
	}
}


/**
 * =============================
 * Functions
 * =============================
 */


/**
 * Rendert die Wohnungsseite (Tabelle)
 */
function renderWohnungen(){

	$context["wohnungen"]   = buildList();
	$context["plugin_url"]  = plugins_url()."/fewo-manager";
	$context["actual_url"]  = $actual_link = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
	Timber::render("wohnungen.html.twig", $context);
}

/**
 * Baut die Tabelle wichtig für renderWohnungen()
 */

function buildList(){

	global $wpdb;
	/*$wohnungen = $wpdb->get_results("SELECT fewo.id as fewo_id, fewo.name, preis, groesse, posts_id  from fewo_wohnungen as fewo LEFT JOIN $wpdb->base_prefix.fewo_bilder on fewo.id = $wpdb->base_prefix.fewo_bilder.fewo_id WHERE $wpdb->base_prefix.fewo_bilder.marker = 1");*/

	$wohnungen = $wpdb->get_results("SELECT fewo.id as fewo_id, fewo.name, preis, groesse from ".$wpdb->base_prefix."fewo_wohnungen as fewo");

	foreach($wohnungen as $key => $val){
		if(isset($wohnungen[$key]->posts_id)){
			$wohnungen[$key]->src = wp_get_attachment_image_src($wohnungen[$key]->posts_id);
		}
	}




	return $wohnungen;
}

/**
 * Baut das Wohnungsformular anhand der WohnungsID
 */
function renderWohnungFormular(){
	$id = $_GET["id"];

	global $wpdb;
	$context = [];
	$context["fewo_data"] = $wpdb->get_row("SELECT * from ".$wpdb->base_prefix."fewo_wohnungen where id = $id");
	$context["plugin_url"]  = plugins_url()."/fewo-manager";
	$context["actual_url"]  = $actual_link = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
	$context["bilder"]      = loadImages();
	Timber::render("wohnungen-formular.twig",$context);

}


/**
 * Legt neue Wohnung in der Datenbank an
 */
function createWohnung(){
	include_once "classes/wohnung.php";
	$wohnung = new wohnung();
	$wohnung->createWohnung();

	renderWohnungen();
}

/**
 * Speichert die Wohnung anhand der WohnungsID
 */
function saveWohnung(){
	include_once "classes/wohnung.php";
	$wohnung = new wohnung();
	$wohnung->saveWohnung($_POST);
}

/**
 * Löscht die Wohnung anhand der WohnungsID
 */
function deleteWohnung(){
	include_once "classes/wohnung.php";
	$wohnungen = new wohnung();
	$wohnungen->deleteWohnung($_POST["id"]);
}

/**
 * Lade nur eine Datei hoch in das Upload verzeichnis 2000/01
 * das Verzeichnis kann unter $time geändert werden
 */
function fileUpload(){
	if( ! function_exists('wp_handle_upload')){
		require_once (home_url() . 'wp-admin/includes/file.php');
	}


	$uploadedfile = $_FILES['file'];

	$upload_overrides = array( 'test_form' => false );
	$time = "2000/01";

	$movefile = wp_handle_upload( $uploadedfile, $upload_overrides ,$time);

	if ( $movefile && ! isset( $movefile['error'] ) ) {
		echo "File is valid, and was successfully uploaded.\n";
		var_dump( $movefile );
	} else {
		/**
		 * Error generated by _wp_handle_upload()
		 * @see _wp_handle_upload() in wp-admin/includes/file.php
		 */
		echo $movefile['error'];
	}
}

/**
 * Upload einer Media-Datei (Image) gleicher Upload wie bei der Mediathek im Admin-Menu
 * Bilder werden in dieser auch angezeigt, in der Datenbank gespeichert und können über die Standard
 * Wordpress funktionen abgerufen werden.
 */
function mediaUpload(){

		// These files need to be included as dependencies when on the front end.
		require_once( ABSPATH . 'wp-admin/includes/image.php' );
		require_once( ABSPATH . 'wp-admin/includes/file.php' );
		require_once( ABSPATH . 'wp-admin/includes/media.php' );

		$attachment_id = media_handle_upload( 'file', $_POST['file'] );

		global $wpdb;

		$queryString = "INSERT INTO ".$wpdb->base_prefix."fewo_bilder (`fewo_id`,`posts_id`) VALUES ('".$_GET["id"]."','".$attachment_id."');";

		$wpdb->query($queryString);

		if ( is_wp_error( $attachment_id ) ) {
			// There was an error uploading the image.
		} else {
			// The image was uploaded successfully!
		}
}

function loadImages(){

	global $wpdb;

	$id = $_GET["id"];
	$images = [];

	$bilder = $wpdb->get_results('SELECT fewo.posts_id, marker FROM '.$wpdb->base_prefix.'fewo_bilder AS fewo LEFT JOIN '.$wpdb->base_prefix.'posts AS wp ON fewo.posts_id = wp.id WHERE fewo.fewo_id = '.$id);

	foreach($bilder as $key => $item){
		$images[$key]["img"] = wp_get_attachment_image($item->posts_id,"fewo-thumb");
		$images[$key]["id"] = $bilder[$key]->posts_id;
		$images[$key]["marker"] = $bilder[$key]->marker;
	}

	return $images;

}

function saveMarker(){

	global $wpdb;

	$id = $_GET["id"];

	$wpdb->query("UPDATE ".$wpdb->base_prefix."fewo_bilder set marker = 0 WHERE fewo_id = ".$_POST["fewoId"]);
	$wpdb->query("UPDATE ".$wpdb->base_prefix."fewo_bilder set marker = 1 WHERE posts_id = ".$_POST["id"]);

}


function deleteImg(){

	wp_delete_attachment($_POST["id"]);

}